services:
  - type: web
    name: home-healthservice-managment-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT api.index:app
    envVars:
      - key: SECRET_KEY
        generateValue: true